name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 */18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: daoud-hussain/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ Daoud-Hussain }}
          MAX_REPOS: ${{ github.repository_count }}
      - name: Commit & Push
        run: |
          git config user.name Daoud-Hussain
          git config user.email daoudhussain302@gmail.com
          git add -A .
          git commit -m "Personal 3d Contributions images updated"
          git push
